### ISSUE TITLE
add module to check prototype ?

### ISSUE THREAD

**Issue by MadManMathew** [Retsly/microservice#12]
Working with @RongxinZhang ran into some issues with exporting a class/prototype where the functions are not tied to the module, they are to the modules prototype.
 - keep as is
 - change to check prototypes

**Comment by slajax** [comment]
@RongxinZhang @MadManMathew Is this still an issue now that Rongxin added the tests for that check for method definitions? Do we need this to stay open and discuss it? I'm not completely sure I understood what is required but it sounds like what Rongxin wrote tests for?

**Comment by RongxinZhang** [comment]
Closing this. Not being discussed.
