### ISSUE TITLE
Feedback around API

### ISSUE THREAD

**Issue by slajax** [Retsly/microservice#2]
@MadManMathew This is looking great. Here's a small API feedback idea.

Currently: 
```js
client.callService('method1', 'args1', 'args2');

client.callServiceWithCallback('method1', 'args1', 'args2', function(err, data){
    console.log('data',data); 
});
```

Possibly: 
```js
client.call('method1', { first: 1, second: 2 });

client.call('method1', { first: 1, second: 2 } function(err, data){
    console.log('data',data); 
});
```
It might be a more sleek implementation if the `call` method could `typeof === arguments[2]` to see if a callback was passed or not and handle the use case automatically. This is used a lot in node as a way to handle callbacks without requiring a second more verbose method. You could still implement this method, but it would just alias the original method and possibly allow for less duplication.

**Comment by MadManMathew** [comment]
@slajax thanks, yeah I thought about that will add.

**Comment by slajax** [comment]
Cool! I'll close this and leave it up to you if you think it's worthwhile.
